#!/usr/bin/env python3


# below is a function containing our code
def main():


    name = input("Enter name: ")

    day = input("Enter day: ")


    
    # display the input back to the user.
    print("Hello " + name + " Happy " + day + "!")
    
# this calls main
main()

